version: "3.8"

services:
  db:
    container_name: BMS-spring-boot-db
    image: postgres:latest
    environment:
      POSTGRES_USER: Rediet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BMS
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5335:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: